name: Run tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    with:
      display: true
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1
      envs: |
        - linux: build_docs
        - linux: py310-test
        - linux: py310-test-viz
        - linux: py311-test-viz
        - linux: py312-test-viz
        - linux: py312-test-devdeps
        - linux: py313-test-viz
        - macos: py310-test-viz
        - macos: py311-test-viz
        - macos: py312-test-viz
        - macos: py313-test-devdeps
        - windows: py310-test-viz
        - windows: py311-test-viz
        - windows: py312-test-viz
        - windows: py313-test-devdeps

